url: https://alkava28.github.io
baseurl: /test/

# Site settings
title: HEO PORTFOLIO
email: alkava28@naver.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: HEO
  pic: 1
  position: Designer
  email: alkava28@naver.com
  phone: 010.7726.7224




# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
