url: https://alkava28.github.io
baseurl: /portfolio/

# Site settings
title: HEO PORTFOLIO
email: alkava28@naver.com
description: "HEO PORTFOLIO"


# Team names, titles and social links
people:
- name: 허근
  pic: 1
  position: Designer
  email: alkava28@naver.com
  phone: 010.7726.7224




# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
